### ISSUE TITLE
Unknown column 'computer' in 'field list'

### ISSUE THREAD

**Issue by justdoit176** [tomolimo/lock#7]
I get this error trying to install the Lock plugin:
" error creating 'Plugin Lock Read-Only Profile' into 'glpi_profiles' table!Unknown column 'computer' in 'field list' "

Am I doing something wrong? Let me know if you need more informations.

GLPI  v. 0.85.4

Thanks

**Comment by tomolimo** [comment]
Bonjour
Pour le moment lock n'est pas adapté à la version 0.85 mais à la version 0.83
Je vais faire le portage d'ici quelques jours.
Merci
Cordialement
Tomolimo


-------- Original message --------
From: Fabio
Date:09/09/2015 17:11 (GMT+01:00)
To: tomolimo/lock
Subject: [lock] Unknown column 'computer' in 'field list' (#7)


I get this error trying to install the Lock plugin:
" error creating 'Plugin Lock Read-Only Profile' into 'glpi_profiles' table!Unknown column 'computer' in 'field list' "

Am I doing something wrong? Let me know if you need more informations.

GLPI v. 0.85.4

Thanks

**Comment by tomolimo** [comment]
Hello
Right now the lock plugin is not adapted to 0.85 version, but only to 0.83 release.
Please wait for few days for me to port it to 0.85 version.
Sorry for my previous post: I did not realized that you wrote in English. ☺
Regards
Tomolimo

-------- Original message --------
From: Fabio
Date:09/09/2015 17:11 (GMT+01:00)
To: tomolimo/lock
Subject: [lock] Unknown column 'computer' in 'field list' (#7)

I get this error trying to install the Lock plugin:
" error creating 'Plugin Lock Read-Only Profile' into 'glpi_profiles' table!Unknown column 'computer' in 'field list' "

Am I doing something wrong? Let me know if you need more informations.

GLPI v. 0.85.4

Thanks

**Comment by tomolimo** [comment]
Hello,
As a first workaround, you may create manually the needed profile:

profile name: "Plugin Lock Read-Only Profile"
given rights: be able to read-only everything

then restart plugin install and enable it: it should be ok.

regards,
Tomolimo

**Comment by justdoit176** [comment]
Thanks a lot Tomolino, I'm not sure what do you mean when you say it should be read-only on everything, but I tried flagging only the "see" options of the profile and now the plugin can be installed.

Thank you

**Comment by tomolimo** [comment]
Yes that's it.
Could you tell me if any troubles occure?
And tell me if you have updated to v3.1.0?

**Comment by justdoit176** [comment]
3.1.0? Not yet.
Ok I'll try it and I'll tell you what I find.

**Comment by tomolimo** [comment]
Don't forget to install 'mhooks' before installing v3.1.0 release

**Comment by justdoit176** [comment]
Ok, 3.1.0 installed on 0.85.4, tomorrow I'll give it a try.
Thanks

**Comment by tomolimo** [comment]
I think there is a problem.
I'll check it tomorrow.
Thank you
Regards Tomolimo

-------- Original message --------
From: Fabio
Date:10/09/2015 17:34 (GMT+01:00)
To: tomolimo/lock
Cc: "Moron, Olivier"
Subject: Re: [lock] Unknown column 'computer' in 'field list' (#7)

Ok, 3.1.0 installed on 0.85.4, tomorrow I'll give it a try.
Thanks

**Comment by tomolimo** [comment]
I confirm: there is a bug for 0.85.x
I'm going to fix it, and I'll publish the fix asap :)
regards,
Tomolimo

**Comment by tomolimo** [comment]
Solved with release 3.2.0, which is compliant to GLPI 0.85.
regards,
Tomolimo
